hostname = *xiaozujian.com,api-weather.andy.works,api.revenuecat.com

# > 112 TopWidgets☆永久VIP（2022-10-30）@ddgksf2013
^https?:\/\/.*xiaozujian\.com\/api\/app\/config\/userConfig url script-response-body https://raw.githubusercontent.com/44maker/QuantumultX/main/Crack/topwidgets.js

# ～ Not Boring 四件套[天气、习惯、日历、时间] 解锁会员权限（2022-11-23）@ddgksf2013
^https?:\/\/api-weather\.andy\.works\/v\d\/\w{13,18}$ url reject-dict
^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/*) url script-echo-response https://raw.githubusercontent.com/44maker/QuantumultX/main/Crack/notboring.js

